(add-to-list 'auto-mode-alist '("\\.gemspec$" . ruby-mode))
(add-to-list 'auto-mode-alist '("\\.god$" . ruby-mode))
(add-to-list 'auto-mode-alist '("\\.rake$" . ruby-mode))
(add-to-list 'auto-mode-alist '("^Rakefile$" . ruby-mode))
(add-to-list 'auto-mode-alist '("^config.ru$" . ruby-mode))
(add-to-list 'auto-mode-alist '("^.autotest$" . ruby-mode))
(add-to-list 'auto-mode-alist '("^Guardfile$" . ruby-mode))
(add-hook 'ruby-mode-hook (lambda() (local-set-key "k" 'self-insert-command))) ; WTF sometimes k isn't k in ruby mode?
(add-hook 'ruby-mode-hook (lambda() (local-set-key (kbd "M-SPC") 'completion-at-point)))
(add-hook 'ruby-mode-hook (lambda() (setq tab-width 2)))
(load "ruby-flymake")
(add-hook 'ruby-mode-hook (lambda() (local-set-key "\C-cd" 'yari)))
