(add-to-list 'auto-mode-alist '("\\.gemspec$" . enh-ruby-mode))
(add-to-list 'auto-mode-alist '("\\.god$" . enh-ruby-mode))
(add-to-list 'auto-mode-alist '("\\.rake$" . enh-ruby-mode))
(add-to-list 'auto-mode-alist '("^Rakefile$" . enh-ruby-mode))
(add-to-list 'auto-mode-alist '("^config.ru$" . enh-ruby-mode))
(add-to-list 'auto-mode-alist '("^.autotest$" . enh-ruby-mode))
(add-to-list 'auto-mode-alist '("^Guardfile$" . enh-ruby-mode))
(add-to-list 'auto-mode-alist '("Gemfile" . enh-ruby-mode))
(add-hook 'enh-ruby-mode-hook 'robe-mode)
(add-hook 'enh-ruby-mode-hook 'ruby-tools-mode)
(push 'ac-source-robe ac-sources)
